-- V4__add_audit_fields_to_all_entities.sql

-- Tabela: pastor_presidente
ALTER TABLE pastor_presidente
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMPTZ,
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

-- Tabela: docente
ALTER TABLE docente
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMPTZ,
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

-- Tabela: periodo_letivo
ALTER TABLE periodo_letivo
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMPTZ,
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

-- Tabela: polo
ALTER TABLE polo
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMPTZ,
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

-- Tabela: curso
ALTER TABLE curso
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMPTZ,
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

-- Tabela: igreja
ALTER TABLE igreja
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMPTZ,
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

-- Tabela: disciplina
ALTER TABLE disciplina
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMPTZ,
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

-- Tabela: equivalencia
ALTER TABLE equivalencia
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMPTZ,
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

-- Tabela: classe
ALTER TABLE classe
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMPTZ,
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

-- Tabela: turma
ALTER TABLE turma
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMPTZ,
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

-- Tabela: discente
ALTER TABLE discente
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMPTZ,
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

-- Tabela: matricula
ALTER TABLE matricula
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMPTZ,
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
