-- Inserção do Curso
INSERT INTO Curso (codigo, nome) VALUES (1, 'Teologia');

-- Inserção das Disciplinas associadas ao curso com id 2
INSERT INTO Disciplina (idcurso, codigo, nome, carga_horaria, tipo) VALUES
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'ADE-001', 'Administração Eclesiástica', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'CCC-001', 'Cosmovisão Cristã e Contemporaneidade', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'EPG-001', 'Epístolas Gerais', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'EPP-001', 'Epístolas Paulinas', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'EST-001', 'Estágio Supervisionado', 160, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'ETC-001', 'Ética Cristã', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'EVG-001', 'Evangelismo e Discipulado', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'ESA-001', 'Evangellhos Sinóticos e Atos', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'EXA-001', 'Exegese do A.T', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'EXN-001', 'Exegese do N.T', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'FAS-001', 'Fundamentos da Assistência Social', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'FEC-001', 'Fundamentos da Educação Cristã', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'FAB-001', 'Fundamentos do Aconselhamento Bíblico', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'GRO-001', 'Grego I', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'GRO-002', 'Grego II', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'HBI-001', 'Hebraico I', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'HBI-002', 'Hebraico II', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'HRM-001', 'Hermenêutica', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'HST-001', 'História da Teologia', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'HSI-001', 'História de Israel', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'HSC-001', 'História do Cristianismo I', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'HSC-002', 'História do Cristianismo II', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'HIB-001', 'História e Identidade Batista', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'HOM-001', 'Homilética', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'COM-001', 'Horas Complementares', 160, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'INB-001', 'Introdução à Bíblia', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'INT-001', 'Introdução a Teologia', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'LTJ-001', 'Literatura Joanina', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'LHA-001', 'Livros Históricos do A.T', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'LPS-001', 'Livros Poéticos e Sapienciais', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'MTP-001', 'Metodologia da Pesquisa', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'MSS-001', 'Missiologia', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'PTC-001', 'Pentateuco', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'PDI-001', 'Plantação e Desenvolvimento de Igrejas', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'PTI-001', 'Português  Instrumental', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'PRI-001', 'Profetismo em Israel', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'PPT-001', 'Projeto de Pesquisa em Teologia', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'RLM-001', 'Religiões Mundiais', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'TLP-001', 'Teologia Pastoral', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'TLS-001', 'Teologia Sistemática I', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'TLS-002', 'Teologia Sistemática II', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'TLS-003', 'Teologia Sistemática III', 40, 'OBG'),
                                                                        ((select id_curso from curso where nome = 'Teologia'), 'TCC-001', 'Trabalho e Conclusão de Curso', 40, 'OBG');