-- Remove a restrição existente
ALTER TABLE Discente DROP CONSTRAINT discente_escolaridade_check;

-- Adiciona a nova restrição com o valor 'Superior completo'
ALTER TABLE Discente
    ADD CONSTRAINT discente_escolaridade_check
        CHECK ( escolaridade IN ('Ensino Médio', 'Superior', 'Superior completo', 'Superior incompleto', 'N/A', '') );

-- INSERTS PARA A TABELA DISCENTE

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista da Esperança' AND pastor_nome = 'Celso Adriano Gibbs'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2018' AND pl.semestre = '1'),
             '2018010101',
             'Vítor de Oliveira e Silva',
             '016.664.784-58',
             'vitordeoliveiraesilva@gmail.com',
             '(84)99912-3905',
             'Cursando',
             'M',
             'Natal, RN',
             'SSP/RN',
             '1998-10-15',
             'Eliabe de Oliveira e Silva / Maria Gizeuda de Oliveira e Silva',
             'Casado(a)',
             'Rua Elizabeth, 53, Casa 01, Dix Sept Rosado, Natal, RN',
             'Superior completo',
             '2018-09-01'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Polo Zona Norte/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Santarém' AND pastor_nome = 'Eliabe de Oliveira e Silva'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2018' AND pl.semestre = '2'),
             '2018020201',
             'Maria Gizeuda de Oliveira e Silva',
             '474.741.654-49',
             'gizaosilva@gmail.com',
             '(84)998188967',
             'Cursando',
             'F',
             'Doutor Severiano RN',
             'SSP/SP',
             '1967-02-16',
             'Antonio Eliezer e Maria da Conceição Filha',
             '',
             'Rua Jeová Shalom 26',
             'Superior completo',
             '2018-08-06'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Polo Zona Norte/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista Jardim Progresso' AND pastor_nome = 'Isaías Herculano'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2023' AND pl.semestre = '1'),
             '2023020101',
             'Guilherme Rodrigues Lourenço Silva',
             '705.167.924-40',
             'guilhermerls07@gmail.com',
             '(84)99658-6292',
             'Cursando',
             'M',
             'N/A',
             'N/A',
             '1999-01-11',
             'Maria Lúcia Lourenço da Silva',
             'Casado(a)',
             'Rua Elza Dias Duarte, 03, Jardins, Sâo Gonçalo, RN',
             'Ensino Médio',
             '2023-04-01'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Polo Zona Norte/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Vera Cruz' AND pastor_nome = 'N/D'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2023' AND pl.semestre = '1'),
             '2023020102',
             'Wantuir Anderson Alves de Araújo',
             '111.588.184-16',
             'wantuiranderson@gmail.com',
             '(84)988238663',
             'Cursando',
             'M',
             'N/A',
             'SSP/RN',
             '1994-06-28',
             'Damiana Alves de Andrade Araújo',
             'Casado(a)',
             'Rua dos Eucaliptos 531',
             'Ensino Médio',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Polo Zona Norte/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista Vera Cruz' AND pastor_nome = 'José Antônio Fonseca'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2023020103',
             'Jair Bento da Silva',
             '161.802.024-27',
             'bentojair045@gmail.com',
             '(84)98767-2150',
             'Cursando',
             'M',
             'N/A',
             'N/A',
             '2022-05-23',
             'Maria José Bento da Silva',
             'Casado(a)',
             'Rua dos Eucaliptos, 558, Centro, Vera Cruz, RN',
             'N/A',
             '2023-04-01'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Polo Zona Norte/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Jardim Brasil' AND pastor_nome = 'Marcos Aurélio'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2023' AND pl.semestre = '2'),
             '2023020201',
             'José Marcos Barbosa',
             '422.847.404-72',
             'marcosbarbosajmb@gmail.com',
             '(84)986092189',
             'Cursando',
             'M',
             'Natal, RN',
             'SSP/RN',
             '1964-10-05',
             'Djanira Silva Barbosa',
             'Casado(a)',
             'Rua Ribeiro Alves 10',
             'Ensino Médio',
             '2023-07-15'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Polo Zona Norte/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Primeira Igreja Batista de Pitangui' AND pastor_nome = 'Rui Torres da Silva'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2023' AND pl.semestre = '2'),
             '2023020202',
             'Lindeberg Santana Lopes',
             '061.041.994-37',
             'lindeberg.slopes@gmail.com',
             '(84)99134-8664',
             'Cursando',
             'M',
             'João Câmara, RN',
             'ITEP/RN',
             '1988-05-03',
             'Manoel Bazilio Lopes / Lucilene da Silva Santana',
             'Casado(a)',
             'Rua José Vieira de Melo, 03, Graçandu/Litorânea, Extremoz, RN',
             'Ensino Médio',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista Jardim Brasil' AND pastor_nome = 'Marcos Aurelio'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2022' AND pl.semestre = '1'),
             '2022010101',
             'Israel Lima Cordeiro',
             '058.589.574-04',
             'ri3tecnomix@gmail.com',
             '(84)98619-6875',
             'Cursando',
             'M',
             'Natal, RN',
             'SSP/RN',
             '1985-01-21',
             'Gilson Alves Cordeiro / Luzimar Januário de Lima Cordeiro',
             'Casado(a)',
             '',
             'Ensino Médio',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Polo Zona Norte/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista do Santarém' AND pastor_nome = 'Eliabe de Oliveira e Silva'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2023' AND pl.semestre = '1'),
             '2023010101',
             'Ismael de Oliveira Lemos',
             '084.732.334-09',
             'ismael.lemos.1997@gmail.com',
             '(84)98879-8975',
             'Cursando',
             'M',
             'Natal, RN',
             'ITEP/RN',
             '1997-03-04',
             'Julio Cesar Javier Lemos / Nezia de Oliveira Batista Lemos',
             'Solteiro(a)',
             'Rua Lírio dos Vales, 29, Pajuçara, Natal, RN',
             'Superior completo',
             '2023-05-31'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Polo Zona Norte/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista em Jardim Petrópolis' AND pastor_nome = 'Eugenio Pacelly Soares de Araújo Sobrinho'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024010201',
             'Mayara Patricia Pinheiro',
             '076.522.564-61',
             'mayarapatriciap@gmail.com',
             '(84)99845-3079',
             'Cursando',
             'F',
             'Natal, RN',
             'SSP/RN',
             '1989-12-13',
             'Espedito Filho / Selma Maria Pinheiro',
             'Casado(a)',
             'Rua das Acácias, 03, Jardim Petrópolis, São Gonçalo do Amarante, RN',
             'Superior completo',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Polo Zona Norte/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista do Santarém' AND pastor_nome = 'Eliabe de Oliveira e Silva'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020201',
             'Chandra Thais Mendes dos Santos',
             '093.102.614-80',
             'chandramendes@gmail.com',
             '(84)99708-0210',
             'Cursando',
             'F',
             'Natal, RN',
             'SSP, RN',
             '1992-04-13',
             'Antônio Gomes dos Santos / Lucia Maria Mendes Honorio',
             'Solteiro(a)',
             'Rua Roldão Augusto Botelho, 475, Lagoa Azul, Natal, RN',
             'Superior completo',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Polo Zona Norte/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista do Santarém' AND pastor_nome = 'Eliabe de Oliveira e Silva'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2018' AND pl.semestre = '2'),
             '2024020202',
             'Luizmar Braga dos Anjos',
             '020.465.304-54',
             'luizmarbraga@gmail.com',
             '(84)99181-1374',
             'Cursando',
             'M',
             '',
             'SSP/PE',
             '1975-09-26',
             'Luiz Noberto dos Anjos / Maria Idalia Braga dos Anjos',
             'Casado(a)',
             'Aveninda Pico do Cabugi 1008, Potengi, Natal, RN',
             'Superior completo',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Polo Zona Norte/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista em Jardim Petrópolis' AND pastor_nome = 'Eugenio Pacelly Soares de Araújo Sobrinho'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020203',
             'Italo Alves de Lima',
             '104.346.954-08',
             'projetos.italoalvesdelima@gmail.com',
             '(84)99944-4365',
             'Cursando',
             'M',
             'Natal, RN',
             'ITEP/RN',
             '1995-02-21',
             'José Edimilson de Lima / Ester Alves da Silva Lima',
             'Casado(a)',
             'Rua Manoel Patrício de Medeiros, 2100 AP-402, Jardins, São Gonçalo do Amarante',
             '',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Primeira Igreja Batista em Extremoz' AND pastor_nome = 'Genilson'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020101',
             'Jorge Antônio de Assis Costa',
             '633.732.203-78',
             'jorgeantoniod2@gmail.com',
             '(84)98859-8195',
             'Cursando',
             'M',
             'Rio de Janeiro, RJ',
             'SSP/RJ',
             '1981-12-07',
             'José Antônio da Costa / Tereza de Assis Costa',
             'Casado(a)',
             'Rua das Cerejeiras, 43, Parque das Jaqueiras, Extremoz, RN',
             'Ensino Médio',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista Água Viva (Bairro Golandim)' AND pastor_nome = 'Diácono João Batista (processodeconcílioparapastorearaIgreja)'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020102',
             'Maria Vitoria Pereira Fernandes Campos',
             '017.968.344-67',
             'vitoriacamposvc16@gmail.com',
             '(84)98861-3419',
             'Cursando',
             'F',
             'Natal, RN',
             'SSP/RN',
             '2000-04-17',
             'João Luiz de Melo Campos / Sueli Pereira Fernandes',
             'Solteiro(a)',
             'Travessa Paulo Coelho Segunda, 35-B, Nossa Senhora da Apresentação, Natal, RN',
             'Superior',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'PIB Parnamirim' AND pastor_nome = 'Carlos França'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020103',
             'Robson de Azevedo Freitas Junior',
             '400.364.228-78',
             'robsonfjunior.22@gmail.com',
             '(84)99897-4876',
             'Cursando',
             'M',
             'São Vicente, SP',
             'ITEP/RN',
             '1993-06-22',
             'Robson de Azevedo Freitas / Mirian Rodrigues da Silva Freitas',
             'Casado(a)',
             'Avenida Doutor Luís Antônio, 374, Centro, Parnamirim/RN',
             'Ensino Médio',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Extensão Patos/PB'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Comunidade Evangélica congregacional' AND pastor_nome = 'Kelton Carneiro Bezerra'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020401',
             'André Pereira da Silva',
             '031.398.934-69',
             'silvandrepereira1379@gmail.com',
             '(83)98105-4537',
             'Cursando',
             'M',
             'Patos, PB',
             'SSP/PB',
             '1979-06-07',
             'João Pereira da Silva / Geralda da Cunha Pereira',
             'Casado(a)',
             'Sit Flores S/Nº, Teixeira, PB',
             'Ensino Médio',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'IBCidade' AND pastor_nome = 'Antonio Targino'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020109',
             'Rodrigo Missao Murai de Souza',
             '277.056.718-75',
             'rodrigomissao@hotmail.com',
             '8498807-0809',
             'Cursando',
             'M',
             'Marília, SP',
             'SSP/SP',
             '1978-12-28',
             'Benedito Carassa de Souza / Clarice Muraí de Souza',
             'Casado(a)',
             'Rua Rodrigues Alves, 1087, Tirol, Natal, RN',
             'Ensino Médio',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Pib Mipobu' AND pastor_nome = 'Sagay'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020104',
             'Orlando Pinheiro de Moura',
             '663.423.174-53',
             'orlandomoura597@gmail.com',
             '(84)99136-4956',
             'Cursando',
             'M',
             'Goianinha, RN',
             'ITEP/RN',
             '1972-04-30',
             'Luiz Pinheiro de Moura / Maria Soares da Silva',
             'Casado(a)',
             'Rua Antonio Matias Modesto, 50, Aniquim, Goianinha, RN',
             'Ensino Médio',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Extensão Goianinha/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'PIB PEDRO VELHO' AND pastor_nome = 'ROBSON FREITAS (INTERINO)'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020301',
             'Jean José de Oliveira Silva',
             '061.825.254-10',
             'jeanprofessor2012@gmail.com',
             '(84)98135-3385',
             'Cursando',
             'M',
             'Canguaretama, RN',
             'ITEP/RN',
             '1984-05-06',
             'Gilberto José de Oliveira / Maria José da Silva',
             'Casado(a)',
             'RUA CUITEZEIRAS N° 97, Pedro Velho, Rn',
             'Superior',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista Cidade' AND pastor_nome = 'Elisafá'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020105',
             'Marcus Vinicius Nunes Silva',
             '135.904.354-37',
             'mvns2406@gmail.com',
             '(84)98732-7759',
             'Cursando',
             'M',
             'Natal, RN',
             'ITEP/RN',
             '2005-06-24',
             'Elieser Nunes Silva / Cláudia Alves da Silva',
             'Solteiro(a)',
             'Rua Maranata, 2225, Apto 407, bloco B, Planalto, Natal, RN',
             'Superior',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'PIBP - Primeira igreja Batista em Parnamirim' AND pastor_nome = 'Carlos França'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020106',
             'Alefe Tomaz de Macedo Silva',
             '104.541.244-90',
             'tomazalefe@gmail.com',
             '(84)99190-8929',
             'Cursando',
             'M',
             'Parnamirim',
             'ITEP/RN',
             '1995-05-06',
             'Alexandre Tomaz da Silva / Alexandra Lima de Macedo Silva',
             'Casado(a)',
             'Rua Parque Parauna, 64, Nova Esperança, Parnamirim',
             'Superior',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Extensão Goianinha/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista em Monte Castelo (atuo na congregação Batista em Brejinho)' AND pastor_nome = 'Daniel Santos'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020302',
             'Danilo Carvalho de Araujo',
             '096.140.684-42',
             'danilo.carvalho.096@ufrn.edu.br',
             '(84)99126-1495',
             'Cursando',
             'M',
             'Natal, RN',
             'SSP/RN',
             '1992-08-04',
             'Francisco Xavier de Araújo / Danila Augusta de Carvalho',
             'Casado(a)',
             'Rua Rei Salomão, 276, Villa dos Reis, Brejinho, RN',
             'Ensino Médio',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista Jordão' AND pastor_nome = 'Lucas Hellen'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020107',
             'André Anderson Silva de Queiroz',
             '016.799.804-83',
             'andrequeiroooz@gmail.com',
             '84991941895',
             'Cursando',
             'M',
             'Natal, RN',
             'SSP/RN',
             '1999-08-20',
             'Elson Dias de Queiroz / Maria de Piedade da Silva',
             'Casado(a)',
             'Rua Serra do Botucatu, 1135, Potengi, Natal, RN',
             'Ensino Médio',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista Potiguar' AND pastor_nome = 'Pr Isaías'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020108',
             'Rui Pinto da Silva',
             '357.784.664-04',
             'ruip3214@gmail.com',
             '(84)988129179',
             'Cursando',
             'M',
             'São José do Campestre, RN',
             'SSP/RN',
             '1963-09-06',
             'Leopoldo Pinto da Silva / Josefa Lucas de Oliveira',
             'Casado(a)',
             'Rua Santo Alto, 1974, Potengi, Natal, RN',
             'Ensino Médio',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'IBCidade' AND pastor_nome = 'Antônio Targino'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020111',
             'Alexandre Estrela Sales',
             '131.821.238-31',
             'sales3esquadrao@gmail.com',
             '(84)99109-2512',
             'Cursando',
             'M',
             'Parnamirim, RN',
             'Comaer/RJ',
             '1971-05-08',
             'Milton Sales Barbosa / Marli Estrela Sales',
             'Casado(a)',
             'Rua Silvino José dos Santos, 31, Nova Parnamirim, Parnamirim, RN',
             'Superior',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja de Deixar no Brasil' AND pastor_nome = 'Fábio simplicio'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020112',
             'Vitor Pereira Silva',
             '109.629.024-38',
             'vitorsilvanavoz@gmail.com',
             '84988450092',
             'Cursando',
             'M',
             'Ceará-Mirim, RN',
             'SSP/RN',
             '1995-06-15',
             'Flavio Pereira da Silva/ Maryjane dos Santos Silva',
             'Casado(a)',
             'Rua São Caetano, 173, Lagoa Azul, Natal, RN',
             'Ensino Médio',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Segunda Igreja Batista de Parnamirim (SIBP)' AND pastor_nome = 'Valtenci Oliveira'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020113',
             'Jadson José Barbosa Avelino',
             '700.563.844-16',
             'jadsonjoseav@gmail.com',
             '84987970302',
             'Cursando',
             'M',
             'Natal, RN',
             'ITEP/RN',
             '1993-12-01',
             'José Avelino Neto / Joselita Barbosa',
             'Casado(a)',
             'Rua Luiza Maria Conceição Santiago, 450, Ap 408, Passagem de Areia, Parnamirim',
             'Ensino Médio',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja batista do alecrim' AND pastor_nome = 'Josoniiel'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020110',
             'Ricardo Riquelme Fernandes de Miranda',
             '875.732.884-68',
             'riquelmericardo250@gmail.com',
             '84981829341',
             'Cursando',
             'M',
             'Mossoró, RN',
             'SSP/RN',
             '1974-04-27',
             'Abdias crispim de Miranda / Wilma Fernandes de Oliveira',
             'Solteiro(a)',
             'Travessa da Cerâmica, 103, Nossa Senhora de Nazaré, Natal, RN',
             'Ensino Médio',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Polo Zona Norte/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista do Santarém' AND pastor_nome = 'Eliabe de Oliveira Silva'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020205',
             'Bruno Alennykov Ramos Soares de Araújo',
             '093.154.574-98',
             'alennykov@gmail.com',
             '84988484086',
             'Cursando',
             'M',
             'Natal, RN',
             'ITEP/RN',
             '1989-08-24',
             'Eugenio Pacelli Soares de Araújo / Maria Gercina Ramos',
             'Casado(a)',
             'Avenida Almirante Alexandrino de Alencar, 900, Ap 1408, Lagoa Seca, Natal, RN',
             'Superior',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Polo Zona Norte/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista do Santarém' AND pastor_nome = 'Eliabe de Oliveira e Silva'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020206',
             'Jeferson Leandro Gomes da Silva',
             '059.694.884-02',
             'jefteologo2@gmail.com',
             '(84)99950-6404',
             'Cursando',
             'M',
             'Natal, RN',
             'ITEP/RN',
             '1985-07-06',
             'Josimar Gomes da Silva / Marielza Bento da Silva',
             'Casado(a)',
             'Rua Professor Celestino Pimentel, 65, Nossa Senhora da Apresentação, Natal, RN',
             'Ensino Médio',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'IB Potiguar' AND pastor_nome = 'Isaías Herculano'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020114',
             'Celso Soares da Silva Júnior',
             '107.924.434-46',
             'canteiroteologico@gmail.com',
             '84996019603',
             'Cursando',
             'M',
             'Natal, RN',
             'ITEP/RN',
             '1997-05-17',
             'Celso Soares da Silva / Sanzia Maria Cosme da Silva',
             'Casado(a)',
             'Rua Anisio de Moura Rolim, 6, Olho D''Água, São Gonçalo do Amarante, RN',
             'Superior',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Polo Zona Norte/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Primeira Igreja Batista Jardim Progresso' AND pastor_nome = 'Isaías Herculano'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020207',
             'Marcones José de lira',
             '785.957.384-91',
             'marconesjl@gmail.com',
             '84986203302',
             'Cursando',
             'M',
             'Ielmo Marinho, RN',
             'SSP/RN',
             '1972-09-16',
             'José Ovídio de Lira / Maria da Conceição de Lira',
             'Casado(a)',
             'Avenida Senador Carlos Alberto, 275, Nossa Senhora da Apresentação, Natal, RN',
             'Ensino Médio',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista Cidade' AND pastor_nome = 'Targino'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020115',
             'Alyson Elias Evangelista Nogueira',
             '076.415.504-01',
             'alysonnogueira084@gmail.com',
             '(84)999842175',
             'Cursando',
             'M',
             'Natal, RN',
             'SDS/PE',
             '1990-06-27',
             'Carlos Alberto Evangelista Nogueira / Ana Catarina da Silva',
             'Casado(a)',
             'Rua do Brilhante, 86, Lagoa Nova, Natal, RN',
             'Ensino Médio',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'IBCidade' AND pastor_nome = 'Antonio de Araújo Targino'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020116',
             'Wilson Cesar Pinto Pessoa',
             '033.797.044-07',
             'wcsppessoa2@gmail.com',
             '84988074534',
             'Cursando',
             'M',
             'Natal, RN',
             'ITEP/RN',
             '1980-03-23',
             'Wilson Sales Pessoa / Severina Dantas Pinto',
             'Casado(a)',
             'Avenida Prudente de Morais, 1610, Tirol, Natal, RN',
             'Superior',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Polo Zona Norte/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista do Santarém' AND pastor_nome = 'Eliabe de Oliveira e Silva'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020208',
             'Ana Karina de Freitas Vasconcelos Mercês',
             '028.354.744-80',
             'annakarinavasconcelos@gmail.com',
             '84988222542',
             'Cursando',
             'F',
             'Natal, RN',
             'ITEP/RN',
             '1978-06-16',
             'José de Góis Vasconcelos / Vilma Maria de Freitas',
             'Casado(a)',
             'Avenida Maranguape, 359, Potengi, Natal, RN',
             'Superior',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista Sinai' AND pastor_nome = 'Edjarde'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2024' AND pl.semestre = '1'),
             '2024020117',
             'Vandré falcone de Andrade',
             '069.635.454-30',
             'vanvafalcone26@gmail.com',
             '84994847595',
             'Cursando',
             'M',
             'Natal, RN',
             'ITEP/RN',
             '1988-09-26',
             'Damião de Andrade / Maria do Socorro de Andrade',
             'Solteiro(a)',
             'Rua Thiago Queiroz, 42, Planalto, Natal, RN',
             'Ensino Médio',
             '2024-12-12'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'IBCidade Elói de Souza' AND pastor_nome = 'Antonio de Araújo Targino'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2025' AND pl.semestre = '1'),
             '2025010101',
             'Diego Santos de Melo Ferreira',
             '099.159.014-70',
             'ibcidadeeloidesouza@gmail.com',
             '84987102517',
             'Cursando',
             'M',
             'Natal, RN',
             'SSP/RN',
             '1993-07-02',
             'Cleone Inácio de Melo / Rosenilda dos Santos Oliveira',
             'Casado(a)',
             'Rua Demétrio Constantino da Silva, 23, Alto da Liberdade, Senador Eloi de Souza, RN',
             'Ensino Médio',
             '2025-01-02'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista Cidade' AND pastor_nome = 'Antonio de Araújo Targino'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2025' AND pl.semestre = '1'),
             '2025010102',
             'Luiz Antonio Lins Filho',
             '011.762.334-24',
             'lins.lalf@gmail.com',
             '8499203-8528',
             'Cursando',
             'M',
             'São Luis, MA',
             'SSP/PB',
             '1981-09-23',
             'Luiz Antonio Lins / Maria José Lima de Farias',
             'Casado(a)',
             'Rua José Bezerra, 70, APTO 102, Barro Vermelho, Natal, RN',
             'Superior',
             '2025-01-03'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'PIB do Farol' AND pastor_nome = 'Jucelino Tavares da Silva'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2025' AND pl.semestre = '1'),
             '2025010103',
             'Raniere de Souza',
             '028.241.064-33',
             'ranieresou@gmail.com',
             '84988642880',
             'Cursando',
             'M',
             'Natal, RN',
             'ITEP/RN',
             '1980-04-06',
             'José Fernando André de Souza / Maria de Fátima de Souza',
             'Casado(a)',
             'Rua Camaragibe, 774, Mãe Luiza, Natal, RN',
             '',
             '2025-01-03'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista do Nova Natal' AND pastor_nome = 'Isaías Herculano'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2025' AND pl.semestre = '1'),
             '2025010104',
             'Marcelo Lopes Fraga',
             '080.530.427-40',
             'marcelofraga862@gmail.com',
             '84988615746',
             'Cursando',
             'M',
             'Rio de Janeiro, RJ',
             'IFP/RJ',
             '1974-08-11',
             'Damião Fraga / Jariadete Lopes Fraga',
             'Casado(a)',
             'Rua das Jitiranas, 862, Lagoa Azul, Natal, RN',
             'Ensino Médio',
             '2025-01-08'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'IBcidade' AND pastor_nome = 'Antônio Targino'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2025' AND pl.semestre = '1'),
             '2025010105',
             'Josué Viana da Silva',
             '034.116.674-00',
             'josueviana.s.79@gmail.com',
             '8499993-9500',
             'Cursando',
             'M',
             'Natal, RN',
             'ITEP/RN',
             '1979-10-26',
             'João Viana da Silva / Maria do Nascimento Viana',
             'Casado(a)',
             'RUA ESCRITOR EULICIO FARIAS LACERDA 1630 AP-201 SERRAMBI II BL 14, Ponta Negra, Natal, RN',
             'Superior',
             '2025-01-10'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Sede Natal/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'PIB NATAL' AND pastor_nome = 'Edison Vicente'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2025' AND pl.semestre = '1'),
             '2025010106',
             'Daniel Juan Barros Pinto',
             '709.089.064-39',
             'danieljbpinto@gmail.com',
             '84987734022',
             'Cursando',
             'M',
             'Natal, RN',
             'ITEP/RN',
             '2003-06-08',
             'Rui Pinto da Silva / Jailza Lima Barros Pinto',
             'Casado(a)',
             'Avenida Antônio Basílio 2977, AP-702, Lagoa Nova, Natal, RN',
             'Superior',
             '2025-01-17'
         );

INSERT INTO discente (
    id_polo,
    id_igreja,
    id_turma,
    matricula,
    nome,
    cpf,
    email,
    telefone,
    situacao,
    sexo,
    naturalidade,
    orgao_emissor,
    data_nascimento,
    filiacao,
    estado_civil,
    endereco,
    escolaridade,
    data_ingresso
) VALUES (
             (SELECT idpolo FROM polo WHERE nome = 'Polo Zona Norte/RN'),
             (SELECT id_igreja FROM igreja WHERE nome = 'Igreja Batista Água Viva em Maracajaú' AND pastor_nome = 'Responsável: Irmão João Batista.'),
             (SELECT t.id_turma FROM turma t JOIN periodo_letivo pl ON t.id_periodo_letivo = pl.id_periodo_letivo WHERE pl.ano = '2025' AND pl.semestre = '1'),
             '2025010201',
             'Altamir Santos Pereira Leite',
             '027.191.594-33',
             'asplgemeo1@gmail.com',
             '84998654093',
             'Cursando',
             'M',
             'Natal, RN',
             'ITEP/RN',
             '1978-05-25',
             'Augusto Pereira Leite / Maria José Leite',
             'Casado(a)',
             'Rua da Paz, R3, Maxaranguape, RN',
             'Superior',
             '2025-02-10'
         );

